version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: prettier
    versions:
    - ">= 2.a, < 3"
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
    - 0.145.0
    - 0.146.0
    - 0.147.0
    - 0.148.0
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.12.7
    - 7.13.8
  - dependency-name: "@babel/plugin-proposal-nullish-coalescing-operator"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: webpack-stream
    versions:
    - 6.1.1
- package-ecosystem: npm
  directory: "/examples/draft-0-10-0/playground"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: handlebars
    versions:
    - ">= 4.7.a, < 4.8"
  - dependency-name: codemirror
    versions:
    - 5.59.1
    - 5.59.2
- package-ecosystem: npm
  directory: "/examples/draft-0-10-0/tex"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - "> 4.44.0, < 4.45"
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.8
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.13.0
  - dependency-name: webpack
    versions:
    - 5.11.1
    - 5.19.0
    - 5.24.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.8
  - dependency-name: "@babel/node"
    versions:
    - 7.12.10
    - 7.13.0
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.1
- package-ecosystem: npm
  directory: "/examples/draft-0-10-0/universal"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
