version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly

- package-ecosystem: npm
  directory: /examples/draft-0-10-0/playground
  schedule:
    interval: monthly

- package-ecosystem: npm
  directory: /examples/draft-0-10-0/tex
  schedule:
    interval: monthly

- package-ecosystem: npm
  directory: /examples/draft-0-10-0/universal
  schedule:
    interval: monthly
